#!/bin/sh
cd /etc/nginx
rm nginx.conf
envsubst '
$$NAMESERVER
$$ADMIN_PORT
$$ADMIN_IM_SERVER_URL
$$ADMIN_IM_MSG_KF_URL
$$ADMIN_IM_WEB_AGENT
$$ADMIN_STAT_SERVER_URL
$$ADMIN_KNOWLEDGE_KBQA_URL
$$ADMIN_KNOWLEDGE_GRAPH_URL
$$ADMIN_ELK_STAT_SERVER_URL
$$ADMIN_SSO_SERVER
$$ADMIN_UTILS_URL
$$ADMIN_SSM_UI_URL
$$ADMIN_SSM_DAC_URL
$$ADMIN_LQCHECK_CONFLICT_CHECK_URL
$$ADMIN_CCS_UI_URL
$$ADMIN_CCS_DAL_URL
$$ADMIN_CCS_DIVERTER_URL
$$ADMIN_CCS_CONTROLLER_URL
' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
/etc/nginx/sbin/nginx -g "daemon off;"
